spring.application.name=dema
spring.profiles.active=local
server.port=8090
server.forward-headers-strategy=native

jwt.secret=8J+5nX9q2Wz7kP4rT8vY3mL6xQ2bN9jF5hR1cK0tZ3pA7uM4wL8yN6vX2sB9qT3
jwt.accessTokenExpirationMs=36000000
jwt.refreshTokenExpirationMs=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= ramasquare22@gmail.com
spring.mail.password= qrlb stfk fxox uzij
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
google.maps.api.key=AIzaSyAzVU1VMcTMAcrfFpdv6nug3I-vN2Tew8U

stripe.secret.key=sk_test_51RDjtYG4jrOmUUqMLiwp9dcStP22qamdcywhPQNzzddMgJqtFIPqyx8J2Knz2goqiY3Tf0YdNdSwLy99nLqYqAHM0037iocdEi
stripe.webhook.secret=whsec_sAWZ1ENkOQLhyZ9J6NC2voBAE1nwDT38


logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.security=DEBUG

app.firebase-configuration.file=firebase.json
spring.data.mongodb.uri=mongodb://localhost:27017/localdema

